# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-12 03:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20160812_0258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='event_id',
        ),
        migrations.RemoveField(
            model_name='prize',
            name='event_id',
        ),
        migrations.AddField(
            model_name='prize',
            name='game_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Game'),
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
