# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-12 03:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20160812_0304'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='game_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Game'),
        ),
    ]
