# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-12 04:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_session_game_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='game_id',
            new_name='game',
        ),
    ]
