# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-12 18:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_question_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='num_answered',
            field=models.IntegerField(default=0),
        ),
    ]
